openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: ?lesson 1?
x-ncr-sec-app: TxApplication
security:
  - ncr-bearer-jwt: []
servers:
  - url: /v1
paths:
  /accounts/{id}:
    get:
      description: Get balance.
      operationId: accounts/getBalance
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object
  /accounts:
    post:
      description: Create Account
      operationId: accounts/createAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '201':
          description: response
          content:
            application/json:
                schema:
                  type: object
    get:
      description: Query Accounts
      operationId: accounts/queryAccounts
      parameters:
      - in: query
        name: customerId
        schema:
          type: integer
        description: Customer Id
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Account'
components:
  securitySchemes:
    ncr-bearer-jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Account:
      type: object
      properties:
        balance:
          type: integer
        id:
          type: integer
        label:
          type: string
        type:
          type: string
          enum:
            - checking
            - savings
